### ISSUE TITLE
Default radius in movex

### ISSUE THREAD

**Issue by NikolasE** [SintefRaufossManufacturing/python-urx#20]
In urrobot.py the movex-helper-function movex sets a radius: (l 307)

`prog = self._format_move(command, tpose, acc, vel, prefix="p", radius=0.02)`

This stops the execution (the UR is probably waiting for the next pose to blend. Only f I remove the radius, functions like back do work.

**Comment by oroulet** [comment]
Are you sure? As far as I know radius is ignored. But if it helps we can
set it to 0

**Comment by NikolasE** [comment]
Sorry, could not reproduce, must have been my mistake at another place
