### ISSUE TITLE
How about 0.11 release for PyPI?

### ISSUE THREAD

**Issue by takahasi** [SintefRaufossManufacturing/python-urx#32]
Hi,
Since urx 0.10.0 in PiPI, many useful changes have been added. Now some APIs are incompatible.
Could you release 0.11.0?
If issues remain for release, I would like to support.

Thanks,

**Comment by oroulet** [comment]
done. Let me know is you find any bugs

**Comment by takahasi** [comment]
Great! Thanks.

I could not find 0.11 in PyPI server. https://pypi.python.org/pypi
Could you upload again?
```shell
python setup.py sdist
twine upload dist/*
```

**Comment by oroulet** [comment]
sorry. fixed a bug in release script

**Comment by takahasi** [comment]
Thanks again!
