### ISSUE TITLE
Do the URRobot and Robot classes need to be separate?

### ISSUE THREAD

**Issue by foohyfooh** [SintefRaufossManufacturing/python-urx#40]
This is just opinion and I am unaware of the reason why you made this design choice.

Since the math3d is a dependency in the setup script does there need to be a safe guard against it not being installed for the Robot class, and by extension can't the Robot classes use of math3d transforms be directly done in the URRobot class?

**Comment by oroulet** [comment]
The issue was the licence. Math3d is gpl... But now I wrote an alternative called m3d which is MIT(on gitlab). I should remove use of math3d. But anyway having two classes is not so bad... One lower level than the other

**Comment by foohyfooh** [comment]
Thank you for clearing up my misunderstanding.
