### ISSUE TITLE
Library exits without math3d

### ISSUE THREAD

**Issue by bauerj** [SintefRaufossManufacturing/python-urx#7]
Currently, math3d is a hard-dependency for the library, as it is imported without a check in urrtmon.py, which - in turn - is imported by urrobot.

**Comment by oroulet** [comment]
OK. Might be. I try to make it independent, but since it is installed on my
PC I forget to check. And writing tests without a robot is hard...

**Comment by bauerj** [comment]
It seems like you already fixed it in eb394d4ebca62f4fa192ed2cb889bb67f560e794 (before I reported this bug :smile: ).

Since math3d now is a dependency on pypi, it should be okay to rely on it being present.
